//Styles.h for advance english dictionary
//authour -Divesh Uttamchandani

#define INPUTHEADER    window(1,22,48,22)
#define INPUTWINDOW    window(1,23,48,25)

#define WORDLISTWINDOW window(50,2,80,21)
#define WORDHEADER     window(50,1,80,1)

#define OUTPUTHEADER   window(1,1,48,1)
#define OUTPUTWINDOW   window(1,2,48,21)

#define USERHEADER      window(50,22,80,22)
#define USERNOTE       window(50,23,80,25)

#define FULLSCREEN     window(1,1,80,25);

#define PARTITION   window(49,1,49,25);

//fonts and colors

/****************************Background Color*****************************/
#define bkcolor             setbkcolor(15)
/*************************************************************************/


/*******************colors and fonts for main menu************************/
#define erasercolor         setcolor(15)	 //same as bkcolor

#define topiccolor          setcolor(4)
#define topicstyle          settextstyle(6,0,6)

#define namecolor_intro     setcolor(2)
#define namecolor_end       setcolor(3)
#define namestyle           settextstyle(6,0,4)
#define th_style            settextstyle(6,0,1)

#define mainmenucolor       setcolor(7)
#define mainmenustyle       settextstyle(6,0,4)
#define menumsgcolor        setcolor(1)
#define menumsgstyle        settextstyle(6,0,3)

#define optionscolor        setcolor(13)
#define optionsstyle        settextstyle(6,0,3)

#define choiceboxcolor      setcolor(4)

#define abtstyle_topic	    settextstyle(6,0,6)
#define abtcolor_topic	    setcolor(4)
#define abtstyle_body	    settextstyle(6,0,4)
#define abtcolor_body	    setcolor(3)
#define abtstyle_msg	    settextstyle(6,0,2)
#define abtcolor_msg	    setcolor(4)

#define thankscolor         setcolor(5)
#define thanksstyle         settextstyle(6,0,6)
/*************************************************************************/

/***********************textbackground etc.for main***********************/
#define txtbkcolor 	    textbackground(2)
#define msgcolor	    textcolor(1)
#define iocolor             textcolor(4)
#define errcolor	    textcolor(4)
/*************************************************************************/
